=== grebetutoring/grebetutoring.com/src/sitemap.schema.json
{
  "$ref": "#/definitions/Sitemap",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Sitemap": {
      "additionalProperties": false,
      "properties": {
        "$schema": {
          "type": "string"
        },
        "homepage": {
          "additionalProperties": false,
          "properties": {
            "markdown": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "target": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "target"
          ],
          "type": "object"
        },
        "navIcon": {
          "additionalProperties": false,
          "properties": {
            "alt": {
              "type": "string"
            },
            "src": {
              "type": "string"
            }
          },
          "required": [
            "src",
            "alt"
          ],
          "type": "object"
        },
        "pages": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "markdown": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "target": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "target"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "version": {
          "enum": [
            "1.0.0"
          ],
          "type": "string"
        }
      },
      "required": [
        "version",
        "navIcon",
        "homepage",
        "pages"
      ],
      "type": "object"
    }
  }
}

=== grebetutoring/grebetutoring.com/src/content/sitemap.json
{
  "$schema": "../sitemap.schema.json",
  "version": "1.0.0",
  "navIcon": {
    "src": "logo_noshadow.png",
    "alt": "Grebe Tutoring"
  },
  "homepage": {
    "name": "Home",
    "target": "/",
    "markdown": "main.md"
  },
  "pages": [
    {
      "name": "Student & Parent Resources",
      "target": "/resources",
      "markdown": "resources.md"
    }
  ]
}
